MODEL:
  TYPE: im_vit
  NAME: im_vit_small_224
  DROP_PATH_RATE: 0.1
  IMVIT:
    MLP_RATIO: 3.
    EMBED_DIM: 192
    DEPTHS: 12
    NUM_HEADS: 12
    PATCH_SIZE: [4,8,16,32]
    CONV_CHANNEL: 12
    SCOPE: [1,4,7]
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20